Repository eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt, pull requests merged in 2024-04, with the labels that each got.

#144 Fix/format
  gradle.properties
  src/main/kotlin/eu/europa/ec/eudi/prex/PresentationMatcher.kt
  src/main/kotlin/eu/europa/ec/eudi/prex/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/prex/internal/InputDescriptorEvaluator.kt
  src/main/kotlin/eu/europa/ec/eudi/prex/internal/Serialization.kt
  src/test/kotlin/eu/europa/ec/eudi/prex/MatcherSample.kt
  src/test/kotlin/eu/europa/ec/eudi/prex/MatcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/prex/PresentationDefinitionSerializationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/prex/PresentationDefinitionTest.kt
  src/test/kotlin/eu/europa/ec/eudi/prex/PresentationSubmissionSerializationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/prex/PresentationSubmissionTest.kt
  src/test/resources/v2.0.0/presentation-definition/fi.json
  src/test/resources/v2.0.0/presentation-definition/pd_sd_jwt_vc.json
Labels: bug, feature

#148 Group and limit dependabot PRs.
  .github/dependabot.yml
Labels: feature

#155 Fix gradle-build-action
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: dependencies, github_actions
